<svelte:head>
    <title>Caste | Gautam Hathi</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous" />
    <style lang="scss">
        @import "../../../lib/thoughts/thoughts.scss";
    </style>
</svelte:head>
<article>
    <h1 id="tufte-css">Issues with <em>Caste</em></h1>
    <p class="subtitle">Why <em>Caste</em> doesn't give caste the full exploration it deserves</p>
    <section>
        <p><span class="newthought">A couple of years ago,</span> I read Isabel Wilkerson’s definitive masterpiece, <em>The Warmth of Other Suns</em>. The book has rightfully received acclaim as a deep exploration of the Great Migration and a wonderfully rich portrait of three people who participated in the migration. It brings into sharp focus not only the epic scale of the migration but also its lasting impacts on specific individuals and communities. And of course the book illustrates very clearly in both sweeping strokes and granular details how racism twisted America into the country it is today.</p>
        <p>The book is not only incredibly well written, but also exhaustively researched and reported over decades. I remember being struck by the fact that Wilkerson did some of the interviews with the main subjects of the book as early as the mid-1990s even though the book itself was not completed and published until 2010. The book paints a vivid, three-dimensional picture of each person it focuses on and considers in great detail the way in which particular manifestations of racism and discrimination impacted their life.</p>
        <p>As a result, I was eager to read Wilkerson’s latest book, <em>Caste</em>, when it was published this year. The descriptions of the book which I saw gave the impression that it examined the universal roots of systems in different societies across the world which are all intended to divide people into higher and lower groups. As the title indicated, one motivating example which the book considered was the caste system in India and in Hinduism. This was of particular interest to me as someone whose family comes from India and who has gotten various, often distorted perspectives on caste in bits and pieces, but rarely if ever in a broader context.</p>
        <p>But when I started reading the book, I was disappointed to find that <em>Caste</em>’s treatment of caste had issues. Wilkerson’s knowledge and research regarding race in the US are hard to match, and the book went into searing detail about the form and effects of a race-based caste structure in the US. Wilkerson also provided a good treatment of the Nazi attempt to implement a caste system in Germany before and during World War II. But when it came to the original caste system among Indians, it was hard to escape the feeling that Wilkerson had not given the same level of thought and attention to caste in India.</p>
        <p>I should pause here and note that while I take some issues with Wilkerson’s treatment of caste in her book, I do not in any way defend the caste system or the way Indians treat race and class. Caste among Indians is a system of oppression with ugly manifestations and no redeeming features. I have heard enough mealy-mouthed apologists for caste who try to explain why it’s not so bad or has silver linings or was much better as it was originally envisioned many years ago. I am not one of those apologists and this is not one of those apologies. The only point I’m trying to make here is that if you want to write about caste among Indians and use the word as the title of your book, then you should probably explore caste more deeply and with more care than just as a prop for your exploration of race in the US.</p>
        <p>Perhaps the first hint I got that Wilkerson hadn’t given caste in India and among Indians the level of thought it deserved is when I read her description of arriving in India. It turns out that despite caste being a major focus of this book which was published in August 2020, Wilkerson’s "first moments on the subcontinent" happened only in January 2018.<label for="sn-caste" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-caste" class="margin-toggle"/><span class="sidenote"><a href="https://www.google.com/books/edition/Caste/J-FqzQEACAAJ?hl=en">Wilkerson, Isabel. <em>Caste: The Origins of Our Discontents</em> (United States: Random House, 2020), 73.</a></span> I couldn’t help but contrast Wilkerson’s decades-long process of gathering material for <em>The Warmth of Other Suns</em> with her going from never setting foot in India to writing and publishing a whole book on caste in roughly two years.</p>
        <p>And then some of Wilkerson’s first descriptions of India are rather strange. She notes, as many travellers to India might, the multitude of roadside shrines which proliferate India’s streets. But rather than simply expressing interest at the phenomenon, Wilkerson says that the shrines "seemed exotic" until she compared them with "the American ritual of spontaneous altars of flowers and balloons at the site of something very different, at the site of an accident or tragedy, as for the young woman killed at the infamous rally in Charlottesville, Virginia, just months before."<label for="sn-charlottesville" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-charlottesville" class="margin-toggle"/><span class="sidenote">Wilkerson, 73</span> It’s hard to understand why WIlkerson linked roadside shrines to killings and tragedies. I can only guess that Wilkerson is making a bad attempt to align her perceptions of India with her narrative about racism in America.</p>
        <p>But Wilkerson’s experiences and thoughts about India are less concerning than her actual exploration of caste in the book. The issues start when she explains her interactions with people at conferences about caste. Wilkerson says that she developed a knack for telling who at a conference was of high caste and who was of low caste simply by looking at the way they carried themselves and their interaction with others. She describes this as her "caste radar".<label for="sn-radar" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-radar" class="margin-toggle"/><span class="sidenote">Wilkerson, 274</span> Wilkerson portrays her caste-detection abilities as strong enough that she seems to be better at figuring out who is of what caste than people from India!</p>
        <p>While Wilkerson’s point that the socialization of caste manifests in ordinary interactions is well taken, her "caste radar" is nevertheless at least a little strange. At best, she seems to be generalizing with a fairly broad brush how people in different castes behave. At worst, she is placing herself as a savior of lower-caste people in a rather patronizing way.</p>
        <p>Even more concerning than Wilkerson’s portrayal of her own interactions with people from different castes, however, is the way she cites people whose experiences she draws on in the book. A number of times throughout the book, Wilkerson relates conversations she has had with people of lower caste and describes their experiences as related to her. She describes these people, often including their demeanor, occupation, and even clothing, but she almost never actually mentions their names, instead saying that they are "upper caste" or "lower caste."<label for="sn-names" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-names" class="margin-toggle"/><span class="sidenote">Some of these people are named in the acknowledgements or endnotes, but not in the main text of the book itself.</span> In contrast, she often mentions by name people whose experience with racism in America she relates.</p>
        <p>Beyond the way in which Wilkerson cites the experiences of people from different castes, her discussion of academic scholarship on caste (or lack thereof) also seems a little shallow. The only scholar on caste whom Wilkerson appears to cite by name throughout the book is <a href="https://en.wikipedia.org/wiki/Bhimrao_Ambedkar">Bhimrao Ambedkar</a>, although a couple others are mentioned in passing. While Ambedkar is an important figure, the contrast is striking with Wilkerson’s exploration of scholarly work on racism in America. She mentions quite a few scholars of race in America multiple times and dives into detail for particular works of scholarship. Wilkerson also seems to feature more prominently a non-academic historian of Nazi Germany and Berlin tour guide, Nigel Dunkley, whom she met in person and mentions by name in the book, than any scholar of caste in India, save perhaps Ambedkar.</p>
        <p>Given Wilkerson’s background and previous work, it does make sense that she gives more space to scholars of race in America. But in a book titled <em>Caste</em>, one might think that the author would make the effort to show the reader a more comprehensive picture of scholarly work on caste and feature scholars of caste more prominently. The fact that Wilkerson doesn’t do this further adds to the sense that she is simply referencing caste in India as needed to make points about racism in America and not exploring it as a topic completely worthy of its own consideration in the book.</p>
        <p>The effects of Wilkerson’s shallow exploration of caste among Indians are not just limited to missing names and sources. There are also a couple of more substantive areas where it shows through. One specific point which stuck out was the case of <a href="https://en.wikipedia.org/wiki/Bhagat_Singh_Thind">Bhagat Singh Thind</a>, which Wilkerson describes in the book when discussing the history of racial caste in America. Thind was an immigrant from India who tried to obtain US citizenship after serving in the US Army, eventually bringing a case to the Supreme Court after the Bureau of Naturalization tried to deny him citizenship.</p>
        <p>According to Wilkerson’s description, Thind was "an immigrant from the dominant caste of India [who] sought to make common cause with his upper-caste counterparts in America when his application for citizenship made it to the Supreme Court."<label for="sn-thind1" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-thind1" class="margin-toggle"/><span class="sidenote">Wilkerson, 126</span> But Bhagat Singh Thind is Sikh, not Hindu, and hence does not fit in to the standard Hindu caste hierarchy. Wilkerson may have been tripped up because Singh’s court filing described him as an upper-caste Hindu, perhaps in order to gain sympathy from racist American courts.<label for="sn-thind2" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-thind2" class="margin-toggle"/><span class="sidenote">The best explanation I’ve been able to find of Thind’s case and the court documents which describe him as "high-caste" is in <a href="https://www.teenvogue.com/story/bhagat-singh-thind-supreme-court-whiteness-citizenship">Teen Vogue</a>.</span> However anyone with even a little knowledge of India and Indians might suspect that someone named "Bhagat Singh Thind" is Sikh, and all it takes is a quick search to confirm.</p>
        <p>WIlkerson’s oversight of Thind’s true religion compared to how he described himself in court documents is particularly disappointing given that one of the points Wilkerson is trying to make in the book is about how people in non-dominant racial castes around the world try to align themselves with the upper caste. She misses an opportunity to add another striking example in favor of her own argument. Indeed, Thind’s story as an immigrant who gained a PhD from Berkeley in theology and served in the army yet had to fight for decades to gain citizenship would make an excellent case study in Caste, similar to many others Wilkerson provides, yet is mostly missing.</p>
        <p>The missed opportunities with regards to caste in India are also broader. For example, Wilkerson skips any discussion of the way in which lower-caste people in India have managed to build and wield political power. This something which might have made an interesting contribution to the section of her book on ways to break down caste structures. Wilkerson spends time discussing the meaning, importance, and potential false hope of a Black man being elected to the highest political office in the US, but does not discuss the elevation of lower-caste people to high office in India, which has become an important, if not completely straightforward, feature of Indian politics.<label for="sn-leadership" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-leadership" class="margin-toggle"/><span class="sidenote">Indeed, India has had more Dalit Chief Ministers leading its states after its independence than the US has had Black state governors in the same time period.</span></p>
        <p>In fact, Wilkerson seems to take a different approach when discussing solutions to caste in India versus in other places. When discussing the US or Germany, she talks about society-wide solutions to caste systems. She discusses how Germany has integrated education about the horrors of Nazism into many aspects of its society and calls for a Truth and Reconciliation Commission in the US to account for the history of racial caste in the US.<label for="sn-solutions" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-solutions" class="margin-toggle"/><span class="sidenote">Wilkerson, 385</span> But with regards to caste in India, Wilkerson tells the story of an individual Brahmin who renounced his caste.<label for="sn-renounced" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-renounced" class="margin-toggle"/><span class="sidenote">Wilkerson, 364</span> Are there not lessons to be learned from India’s societal struggle against caste, as there seem to be in the US and Germany? Or should we conclude that progress against caste in India is individual, not societal?</p>
        <p>All of this taken together gives the impression that while Isabel Wilkerson titled her book Caste, she wasn’t really all that interested in caste. Rather, she seems to rely on caste among Indians as a way to provide examples and comparisons for her exploration of racial caste structure in the United States. By itself, this might make some sense, as Wilkerson is clear that the book has its origins in her attempt to understand the basis of racism in America. But it becomes difficult to use <em>Caste</em> as the title of the book and claim that the goal of the book is to "reach out across the oceans" in order to "understand the origins and evolution of classifying and elevating one group of people over another and the consequences of doing so".<label for="sn-oceans" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-oceans" class="margin-toggle"/><span class="sidenote">Wilkerson, 27</span> A deeper and more considered exploration of caste among Indians might have helped Caste to get closer to that goal.</p>
    </section>
</article>