<svelte:head>
    <title>Media Internships | Gautam Hathi</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous" />
    <style lang="scss">
        @import "../../../lib/thoughts/thoughts.scss";
    </style>
</svelte:head>
<article>
    <h1 id="tufte-css">Hiring in Journalism is Behind the Times</h1>
    <p class="subtitle">News organizations need to stop abusing the internship-to-job pathway</p>
    <section>
      <p>Journalism is built on interns.</p>
      <p>Aside doing the grunt work of news organizations, interns provide journalism’s next generation of talent. But journalism makes it very difficult for interns to actually get into journalism full-time. And while some of that trickiness is due to the <a href="https://www.pewresearch.org/fact-tank/2019/07/09/u-s-newsroom-employment-has-dropped-by-a-quarter-since-2008/">lack of jobs in the news industry</a>, a good deal of it comes from the antiquated, counterproductive, and unfair ways that the media industry sets up its internship-to-job pathway.</p>
      <p>I found this out firsthand when I interned at The New York Times. I was an intern on the interactive news desk, and did a lot of <a href="https://open.nytimes.com/how-the-new-york-times-uses-software-to-recognize-members-of-congress-29b46dd426c7">fun and interesting work</a> while there. I loved my time at the Times, but found out that the process of getting a job at the Times or at any of the other major news organizations is...well...behind the Times.<label for="sn-bad-pun" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-bad-pun" class="margin-toggle"/><span class="sidenote">I promise this is the last bad pun.</span></p>
      <p>An internship is one of the few good ways to get a job at the Times if you are not already established in journalism (and the places you can start a career in journalism outside the major news outlets are fast dwindling). The idea is that you take an internship after graduation, you do good work, and then you get hired. But the internship-to-job pathway has major issues. </p>
      <p>While I was an intern, I attended a panel discussion where four or five former Times interns who were later hired as full-time employees talked about how they made the conversion from intern to full-time. Each of these interns had done great work and their editors wanted to hire them. But in almost every case, the former interns said that they didn’t get a full-time job offer during or right after their internship. Instead they had to take a series of 10-week internship extensions, sometimes for months on end, in the hopes that a full-time job slot would eventually open up. I’ve heard similar stories from people who have done internships at other major news organizations.</p>
      <p>On the face of it, that might not seem like such a bad thing. Premier news organizations are willing to give promising interns continuing opportunities until they have a full-time spot for them. But what extendable internships actually do is allow these organizations to shift the cost of uncertainty onto their interns while making it hard for the organizations to build a staff with diverse backgrounds.</p>
      <p>Hiring a full-time employee is a risk for any company. Companies have to be sure that they will have the money to pay the employee and work to keep the employee busy not just now, but years into the future. Interns, on the other hand, generally cost much less (especially when you consider things like benefits<label for="sn-benefits" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-benefits" class="margin-toggle"/><span class="sidenote">The Kaiser Family Foundation <a href="https://www.kff.org/report-section/ehbs-2019-section-1-cost-of-health-insurance/">estimates</a> that in 2019 employers paid an average of $7,188 per employee in health insurance premiums alone.</span>) and can be let go in a few weeks if money or work dries up. So it’s understandable that a news organization would want to extend an internship rather than make the commitment required to hire an intern full-time.</p>
      <p>However, while extending an internship is beneficial for the employer, it imposes added costs on the intern. Rent is really expensive<label for="sn-rent" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-rent" class="margin-toggle"/><span class="sidenote">[citation needed]</span> if you’re signing leases for two or three months rather than a full year. This is especially true in cities with a high cost of living like New York or DC, and while interns may be able to take advantage of <a href="https://www.nyu.edu/summer/housing/">discounted housing options</a> available during the summer, those options can be a lot harder to find once the summer internship season ends. Interns may also find themselves in an awkward position when looking for other opportunities at the same time as they are trying to convert their extendable internship into a full-time job. No one wants to be caught job hunting while also hoping their current employer will keep employing them. In this way, the extendable intern is worse off than a freelancer, strangely enough, since at least when freelancing there is no implicit expectation that you are only focused on work for one organization.</p>
      <p>Some might say that bearing these costs is just a way of showing that you really want to work at the Times or some other major news organization. All the obstacles that interns face are just ways for prominent journalism organizations to separate the truly committed from the merely interested. If you don’t like what you’re being offered, there are a dozen people willing to take your spot. And at least the Times does pay its interns a reasonable salary, which is more than you can say for many media companies.<label for="sn-intern-pay" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-intern-pay" class="margin-toggle"/><span class="sidenote">Indeed, there are apparently media organizations who think it's just fine to hire <a href="https://www.thecut.com/2018/07/i-was-an-unpaid-intern-at-30.html">30-year-olds with graduate degrees</a> as unpaid interns.</span></p>
      <p>One problem with viewing journalism hiring through this rather Darwinian lens is that the current system optimizes for the wrong things. It favors people who have easy access to housing in New York or DC because their families are close by. It favors people who are able to pay higher rents and take a lesser salary for months on end because they are financially secure. It favors people who don’t need to hold a permanent job because they don’t need to worry about finding and keeping a work visa.</p>
      <p>None of these attributes make someone a better journalist, and indeed in some cases they might actively select for worse candidates. If a news organization is wondering why most of its newsroom employees are upper middle class people with strong ties to New York or DC, perhaps a hiring process that favors financial stability and location in those cities is part of the reason. And while a newly graduated international student on a visa might make for a great journalist with a different perspective, it seems difficult for that type of candidate to pursue a full-time job at the Times via an internship. If the Times and other premier news outlets really want to hire the best candidates, then they should adjust their hiring pathway (which internship conversion is a key part of) to avoid losing people who could potentially be the best candidates.</p>
      <p>And of course, transferring costs onto interns is not only a bad way to hire, it’s also unfair. The Times is a publicly traded company with hundreds of millions of dollars<label for="sn-revenue" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-revenue" class="margin-toggle"/><span class="sidenote"><a href="https://investors.nytco.com/press/press-releases/press-release-details/2020/2019-was-a-Record-Year-for-Digital-Growth-at-The-New-York-Times-Company/default.aspx">and trending quickly towards a billion dollars</a></span> in revenue and thousands of employees. The Times and other major news organizations which hire interns should just hire the people they want to hire, not string them along for as long as they can at half price on 10-week contracts. While the news industry has seen some financial hard times, the biggest names in legacy journalism, including the Times, <a href="https://techcrunch.com/2019/02/06/profits-at-the-new-york-times-show-media-dinosaurs-are-ruling-the-internet/">have returned to profitability on the basis of surging subscriptions.</a> There’s even less reason now to put the cost of hiring uncertainty on interns than there was before.</p>
      <p>It’s worth noting that each intern at the Times has a different experience, and interns at other top tier news organizations have still more different experiences. I know interns at the Times and at other news organizations who have been given a job offer during or right after their internship. But, as I understand it, they just got lucky and that is not the norm even for high performing interns.</p>
      <p>This broken hiring process makes me worried for the Times and the other papers of record that I greatly respect and want to see thrive. The era where the Times could succeed simply because it is the Times is long gone, and the Times knows this well. In order for news organizations (even the premier ones) to succeed, they will need to be aggressive about hiring and developing a diverse and talented staff. Any hiring process which creates obstacles to that could threaten journalism’s ability to survive and thrive.</p>
      <p><i>Update:</i><br> After I wrote this, the Times replaced newsroom internships with <a href="https://www.nytimes.com/interactive/2018/jobs/times-fellowship.html">year-long early-career fellowships</a> that include benefits. This is a step forward, but there are still issues with this new setup: First, although the new fellowships do provide benefits, I'd assume they pay less then what an entry-level reporter would make and still leave highly qualified journalists without a permanent job. This still makes the fellowship look like an way for the Times to get the benefit of great journalists on their staff at an unfairly discounted price, even if there is less of a discount than with an internship. Second, at least some of the fellowship job postings say that ideal applicants will have multiple previous journalism internships, which means that applicants for these fellowships may have to run the extendable internship gauntlet before they have a chance at a year-long fellowship. And of course, while the Times now has fellowships instead of internships in the newsroom, most other news organizations, including many with access to substantial financial resources, have not moved to such a setup.</p>
    </section>
</article>